### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by easysolvz** [matthenning/eloquent-api-filter#1]
Hi,

Is there anything to be loaded in Config/App.php as i am getting an error Trait 'App\Http\Controllers\Matthenning\EloquentApiFilter\Traits\FiltersEloquentApi' not found.

Any help please?

**Comment by rustyricky** [comment]
It looks like you're trying to load the Trait from a relative namespace.
The fully qualified trait name should be `Matthenning\EloquentApiFilter\Traits\FiltersEloquentApi` instead of `App\Http\Controllers\Matthenning\EloquentApiFilter\Traits\FiltersEloquentApi`.
Could you show your code? Maybe you need a leading backslash: `\Matthenning\EloquentApiFilter\Traits\FiltersEloquentApi`

**Comment by easysolvz** [comment]
Hi Mat,

THank for this great piece of work.

Is there a way where we can put filters in the with[] and also return specific columns from the with[]?

Thanks

**Comment by rustyricky** [comment]
Sounds like a good idea, thank you for the suggestion.
I've created a separate feature request issue here: #2
